# **Amin Fathi / 400722102**

In [1]:
pip install torch torchvision

In [4]:
import torch
print(torch.__version__)

1.10.0+cu111


# **Problem 3.a**

In [5]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [6]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [8]:
X<Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [9]:
X>Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [105]:
a1 = torch.randn(2, 3, 3)
b1 = torch.randn(2, 3, 3)

In [106]:
print("a1 is : " ,a1)

a1 is :  tensor([[[ 0.3682,  1.2486, -0.8974],
         [ 0.5905, -0.6181,  0.1003],
         [-0.1786,  0.1607,  0.3776]],

        [[ 0.1538,  0.3202,  1.6721],
         [-0.1790, -0.3078,  1.9797],
         [ 0.5348, -0.8462,  0.1426]]])


In [107]:
print("b1 is : " ,b1)

b1 is :  tensor([[[ 0.9134, -1.9298,  0.3584],
         [ 0.0765,  1.0331, -2.7999],
         [ 1.4186,  1.1320,  0.0271]],

        [[-0.7812, -0.8303, -2.1633],
         [ 0.4146, -0.9341,  0.0194],
         [-1.4283, -0.3302, -0.0236]]])


In [108]:
a1 + b1

tensor([[[ 1.2816, -0.6811, -0.5390],
         [ 0.6670,  0.4149, -2.6995],
         [ 1.2400,  1.2927,  0.4047]],

        [[-0.6274, -0.5101, -0.4912],
         [ 0.2356, -1.2419,  1.9991],
         [-0.8935, -1.1764,  0.1190]]])

In [109]:
a2 = torch.randn(2, 4, 3)
b2 = torch.randn(2, 3, 3)

In [110]:
print("a2 is : " ,a2)

a2 is :  tensor([[[-1.1271,  0.4227,  0.7973],
         [ 0.8409, -0.7177, -1.0686],
         [-1.5106,  1.4640, -2.3686],
         [-0.1523, -0.3926,  1.1293]],

        [[ 1.2625,  1.5082, -0.0754],
         [-0.5544, -0.8997,  1.4911],
         [ 0.5425, -0.3502, -1.6006],
         [ 1.3745, -1.2976,  0.2387]]])


In [111]:
print("b2 is : " ,b2)

b2 is :  tensor([[[ 1.6258, -0.1811, -0.4063],
         [ 0.7607, -1.8106,  0.1626],
         [-0.3798,  0.4725, -1.2554]],

        [[-0.5511, -0.7853, -0.4899],
         [-0.2179, -0.2276, -1.3092],
         [ 0.3244, -1.4059, -0.6300]]])


In [113]:
a2 + b2

RuntimeError: ignored

In [116]:
a3 = torch.randn(3, 3, 3)
b3 = torch.randn(2, 3, 3)

In [117]:
a3 +  b3

RuntimeError: ignored

In [118]:
a4 = torch.randn(2, 3, 6)
b4 = torch.randn(2, 3, 3)

In [119]:
a4 + b4

RuntimeError: ignored

In [149]:
a5 = torch.randn(1, 3, 1)
b5 = torch.randn(2, 3, 3)

In [150]:
print("a5 is :" , a5)
print("b5 is : " , b5)

a5 is : tensor([[[ 0.3255],
         [-1.0365],
         [ 0.7870]]])
b5 is :  tensor([[[-0.3455, -0.2843,  0.8249],
         [ 1.6197,  1.5869,  1.0632],
         [-0.3041,  0.1351, -2.0956]],

        [[-0.9203,  0.3144,  0.1861],
         [ 0.3073,  0.0696, -1.3231],
         [ 0.4849,  0.7784, -0.7234]]])


In [152]:
z5 = a5 + b5

In [153]:
z5

tensor([[[-0.0200,  0.0412,  1.1504],
         [ 0.5831,  0.5503,  0.0266],
         [ 0.4829,  0.9221, -1.3085]],

        [[-0.5948,  0.6399,  0.5116],
         [-0.7292, -0.9669, -2.3597],
         [ 1.2719,  1.5655,  0.0637]]])

In [154]:
z5 - b5

tensor([[[ 0.3255,  0.3255,  0.3255],
         [-1.0365, -1.0365, -1.0365],
         [ 0.7870,  0.7870,  0.7870]],

        [[ 0.3255,  0.3255,  0.3255],
         [-1.0365, -1.0365, -1.0365],
         [ 0.7870,  0.7870,  0.7870]]])

# **Problem 3.b**

In [93]:
import pandas as pd
import tensorflow as tf

In [94]:
dataset = {
    'column1':[0 , 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 ],
    'column2':[0 , 2 , 4 , 6 , 8 , 10 , 12 , 14 , 16 , 18 ],
    'column3':  pd.Series([0 , 3 , 6 , 9 , 12 , 15] , index = [0 , 1 , 2 , 7 , 8 ,9]),
    'column4':  pd.Series([0 , 3 , 4 , 12 , 2, 3 ] , index = [0 , 1 , 2 , 7 , 8 ,9]),
    'column5':  pd.Series([1 , 1 , 1, 1, 1 ,1] , index = [0 , 1 , 2 , 7 , 8 ,9]) ,
    'column6':  pd.Series([3 ,3 ] , index = [0 , 1 ]),
    'column7':  pd.Series([4 ,4 ,4] , index = [0 , 1 , 2 ]), 
    'column8':  pd.Series([10 ,10] , index = [0 , 1]),
}

In [95]:
dataframe = pd.DataFrame(dataset, index = [0,1,2,3,4,5,6,7,8,9] )
print(dataframe)

   column1  column2  column3  column4  column5  column6  column7  column8
0        0        0      0.0      0.0      1.0      3.0      4.0     10.0
1        1        2      3.0      3.0      1.0      3.0      4.0     10.0
2        2        4      6.0      4.0      1.0      NaN      4.0      NaN
3        3        6      NaN      NaN      NaN      NaN      NaN      NaN
4        4        8      NaN      NaN      NaN      NaN      NaN      NaN
5        5       10      NaN      NaN      NaN      NaN      NaN      NaN
6        6       12      NaN      NaN      NaN      NaN      NaN      NaN
7        7       14      9.0     12.0      1.0      NaN      NaN      NaN
8        8       16     12.0      2.0      1.0      NaN      NaN      NaN
9        9       18     15.0      3.0      1.0      NaN      NaN      NaN


In [96]:
dataframe.columns

Index(['column1', 'column2', 'column3', 'column4', 'column5', 'column6',
       'column7', 'column8'],
      dtype='object')

In [97]:
dataframe

column1  column2  column3  column4  column5  column6  column7  column8
0        0        0      0.0      0.0      1.0      3.0      4.0     10.0
1        1        2      3.0      3.0      1.0      3.0      4.0     10.0
2        2        4      6.0      4.0      1.0      NaN      4.0      NaN
3        3        6      NaN      NaN      NaN      NaN      NaN      NaN
4        4        8      NaN      NaN      NaN      NaN      NaN      NaN
5        5       10      NaN      NaN      NaN      NaN      NaN      NaN
6        6       12      NaN      NaN      NaN      NaN      NaN      NaN
7        7       14      9.0     12.0      1.0      NaN      NaN      NaN
8        8       16     12.0      2.0      1.0      NaN      NaN      NaN
9        9       18     15.0      3.0      1.0      NaN      NaN      NaN

In [98]:
flag=0
index =[] 
for i in dataframe.columns:
  if sum(dataframe[i].isna()) >= flag :
    flag = sum(dataframe[i].isna())
for i in dataframe.columns:
  if sum(dataframe[i].isna()) == flag :
    index.append(i) 
print(index)
print(flag)

['column6', 'column8']
8


In [99]:
dataframe = dataframe.drop(index , axis =1 )

In [100]:
dataframe

column1  column2  column3  column4  column5  column7
0        0        0      0.0      0.0      1.0      4.0
1        1        2      3.0      3.0      1.0      4.0
2        2        4      6.0      4.0      1.0      4.0
3        3        6      NaN      NaN      NaN      NaN
4        4        8      NaN      NaN      NaN      NaN
5        5       10      NaN      NaN      NaN      NaN
6        6       12      NaN      NaN      NaN      NaN
7        7       14      9.0     12.0      1.0      NaN
8        8       16     12.0      2.0      1.0      NaN
9        9       18     15.0      3.0      1.0      NaN

In [101]:
tensorflow1 = tf.convert_to_tensor(dataframe)

In [102]:
tensorflow1

<tf.Tensor: shape=(10, 6), dtype=float64, numpy=
array([[ 0.,  0.,  0.,  0.,  1.,  4.],
       [ 1.,  2.,  3.,  3.,  1.,  4.],
       [ 2.,  4.,  6.,  4.,  1.,  4.],
       [ 3.,  6., nan, nan, nan, nan],
       [ 4.,  8., nan, nan, nan, nan],
       [ 5., 10., nan, nan, nan, nan],
       [ 6., 12., nan, nan, nan, nan],
       [ 7., 14.,  9., 12.,  1., nan],
       [ 8., 16., 12.,  2.,  1., nan],
       [ 9., 18., 15.,  3.,  1., nan]])>