In [ ]:
import numpy as np
import pandas as pd

In [ ]:
input =  np.array([[2,-1]])
Y_true=[1 , 0.5 ]
weights1 = np.array([[1 , -0.5 ] , [ 0.5 , -1 ]])
weights2 = np.array([[0.5 , -1 ] , [-0.5 , 1 ]])
bias1 = np.array([[0.5 , -0.5]])
bias2 = np.array([[-1 , 0.5]])
inputsback = [[2] , [-1]]

In [ ]:
def forward(inputs):
  Z = np.dot(inputs , weights1) + bias1 
  H = Relu(Z)
  O = np.dot(H , weights2) + bias2
  return O 

def MSE(x):
  x = x.tolist()
  return np.square(np.subtract(Y_true,x)).mean()

def Relu(x) :
  for i in range(len(x)):
    for j in range(len(x[0])):
      x[i][j] = max(0 ,  x[i][j] )
  return x

In [ ]:
forward(input)

array([[ 0. , -1.5]])

In [ ]:
MSE(forward(input))

2.5

In [ ]:
def MSEgrad(x ):
  x = x.tolist()
  return np.subtract(x , Y_true)

In [ ]:
def Relugrad(x ):
  for i in range(len(x)):
    for j in range(len(x[0])):
      if x[i][j] >0 :
        x[i][j] = 1
      else:
        x[i][j] = 0

  return x

In [ ]:
def weights_grad(weights , i , j):
  return weights[i-1][j-1]

In [ ]:
def update(weights , derivative , leraning_rate = 0.1 ) :
  output = weights - (leraning_rate * derivative)
  return output

In [ ]:
MSEgrad(forward(input))

array([[-1., -2.]])

In [ ]:
def backward(outputs):
  grad_e = MSEgrad(outputs)
  u1 = np.dot(grad_e , weights2.T) 
  hossein = np.dot(input , weights1) + bias1
  ans2 =u1 * Relugrad( hossein)
  weightderivative = np.dot(inputsback ,ans2 )
  weightupdate =  update(weights1 , weightderivative)
  return (weightupdate)


In [ ]:
backward(forward(input))

array([[ 0.7 , -0.5 ],
       [ 0.65, -1.  ]])